{"name": "Проверка ошибки создания юзера: повторное создание существующего юзера", "status": "passed", "start": 1699698234761, "stop": 1699698235262, "uuid": "e7dbca32-808c-4a71-805f-c93b98129278", "historyId": "261d3a732b6c1a88954212563e36c67b", "testCaseId": "261d3a732b6c1a88954212563e36c67b", "fullName": "tests.test_user_register.TestUserRegistration#test_register_duplicate_user_failed_registration", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_register"}, {"name": "subSuite", "value": "TestUserRegistration"}, {"name": "host", "value": "MacBook-Pro-Evgeniya.local"}, {"name": "thread", "value": "1915-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_register"}]}